# fly.toml app configuration file generated for asistencia-mqtt on 2025-04-21T23:39:35-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'asistencia-mqtt'
primary_region = 'mia'

[build]
  image = 'eclipse-mosquitto:2'

[[mounts]]
  source = 'mqttdata'
  destination = '/mosquitto/data'

[[services]]
  protocol = 'tcp'
  internal_port = 1883
  ports = []

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
